### ISSUE TITLE
Binary for windows

### ISSUE THREAD

**Issue by Gavin-Holt** [franko/graph-toolkit#8]
Hi

Any chance of a version 1.0 binary for windows (preferably without the dependency upon pthreadGC2.dll) ? I can't get the current source to compile using TDM-GCC Compiler Suite for Windows Series 5.

Many thanks

Gavin

**Comment by franko** [comment]
Hi there. This is a very old request. Actually I can provide now binaries for windows, for Lua 5.1, 5.4 and luajit 2.1 but I am wondering if that is still useful.

**Comment by Gavin-Holt** [comment]
Hi,

I am still looking for a good data graphing package. Time has moved on, and my Lua installation is now 64bit Luajit from the Open Resty project ([openresty-1.25.3.1-win64.zip]( https://openresty.org/download/openresty-1.25.3.1-win64.zip)), with some DLLs from other sources:

```bat
O:\MyPrograms\DEV\LuaJIT64\luajit.exe
O:\MyPrograms\DEV\LuaJIT64\wlua5.1.exe
O:\MyPrograms\DEV\LuaJIT64\jsmin.dll
O:\MyPrograms\DEV\LuaJIT64\vararg.dll
O:\MyPrograms\DEV\LuaJIT64\struct.dll
O:\MyPrograms\DEV\LuaJIT64\lfs.dll
O:\MyPrograms\DEV\LuaJIT64\libpaths.dll
O:\MyPrograms\DEV\LuaJIT64\lpeg.dll
O:\MyPrograms\DEV\LuaJIT64\cjson.dll
O:\MyPrograms\DEV\LuaJIT64\lpeglabel.dll
O:\MyPrograms\DEV\LuaJIT64\vcruntime140.dll
O:\MyPrograms\DEV\LuaJIT64\ldecnumber.dll
O:\MyPrograms\DEV\LuaJIT64\msvcrt.dll
O:\MyPrograms\DEV\LuaJIT64\lua5.1.dll
O:\MyPrograms\DEV\LuaJIT64\lua51.dll
O:\MyPrograms\DEV\LuaJIT64\terra.dll
O:\MyPrograms\DEV\LuaJIT64\lanes\core.dll
O:\MyPrograms\DEV\LuaJIT64\mime\core.dll
O:\MyPrograms\DEV\LuaJIT64\socket\core.dll
O:\MyPrograms\DEV\LuaJIT64\vcl\core.dll
```
Like many users, I have standardized on Luajit rather than keeping up with the multiple PUC Lua version.

If you have a binary DLL that will work with this compilation of Luajit I would still be interested, otherwise please feel free to  close this issue.

I still believe Lua is suitable for non-compiling users, but hunting down _batteries to fit_ is not easy. 

Kind Regards Gavin Holt 
PS Lite XL is awesome.

**Comment by franko** [comment]
Thank you for sharing these insights, that's interesting to known.

With the new build system, graph-toolkit builds easily with LuaJIT as well as with Lua 5.1 or 5.4.

I may provide binaries but I have the impression that very few people will have a use for them and the binaries I may provide may be incompatible with, for example, those provided by openresty. Probably it is better left to each "distribution" to include graph-toolkit by themselves if they choose so.

I may just provide some binaries just for people that may want to try it out to see how the graph-toolkit works. I will think about that, I am not in a hurry to close this issue :-)

Kind regards
Francesco

**Comment by Gavin-Holt** [comment]
Many thanks, close now.
